# Generated by Django 6.1 on 2026-09-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loraApi', '0029_multiple_daily_sales_report_times'),
        ('loraApi', '0029_productdeletionrequest'),
    ]

    operations = []
