# Generated by Django 6.1 on 2026-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRecord',
            fields=[
                ('deletion_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_no', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(default='delete', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='unknown', max_length=100)),
                ('deleted_from_main', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('deleted_rows', models.IntegerField(blank=True, null=True)),
                ('confirmed_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
